# Dockerfile.producer (Kafka Producer)

FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install netcat for waiting logic (used by docker-compose entrypoint)
RUN apt-get update && \
    apt-get install -y netcat-traditional && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copy the updated kafka_app folder
COPY kafka_app/ kafka_app/

# Install Python dependencies
RUN pip install kafka-python python-dotenv

# Default command (overridden by docker-compose entrypoint)
CMD ["python", "kafka_app/producer.py"]
