# Dockerfile.consumer (Kafka Consumer)

FROM python:3.12-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the updated kafka_app folder into the container
COPY kafka_app/ kafka_app/

# Install Python dependencies for the consumer
RUN pip install kafka-python pymongo python-dotenv

# Run the consumer script
CMD ["python", "kafka_app/consumer.py"]
